<nav class="navbar fixed-top mb-10 h1" id="corCabecalho">

  <span class="navbar-brand"><img id="imagem" src="../Logo/Colorido/Sem_Fundo/Logo_Cultive_Pequeno_407px_407px.png"/></span>

  <p class="titulo1">Cultive - Jardim Colaborativo</p>

  <div class="float-right">
    <div class="btn-group" role="group" aria-label="Grupo de botões com dropdown aninhado">
      <button type="button" class="btn btn-primary custom-btn" data-toggle="modal" data-target="#ModalLogin">
        Login
      </button>
      <button type="button" class="btn btn-primary custom-btn" data-toggle="modal" data-target="#ModalCadastrarUsuario">
        Cadastrar
      </button>
    </div>
  </div>

</nav>